---
- name: Install Nginx on Ubuntu
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes
