---
- name: Install Nginx on Ubuntu Server
  hosts: ubuntu_servers
  become: true
  vars:
    nginx_service: nginx

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: "{{ nginx_service }}"
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: true
